// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<frc::SpeedController> RobotMap::drivebaseSubLFVictorSP;
std::shared_ptr<frc::SpeedController> RobotMap::drivebaseSubLBVictorSP;
std::shared_ptr<frc::SpeedController> RobotMap::drivebaseSubRFVictorSP;
std::shared_ptr<frc::SpeedController> RobotMap::drivebaseSubRBVictorSP;
std::shared_ptr<frc::SpeedControllerGroup> RobotMap::drivebaseSubSpeedControllerGroup1;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    drivebaseSubLFVictorSP.reset(new frc::VictorSP(0));
    lw->AddActuator("DrivebaseSub", "LFVictorSP", std::static_pointer_cast<frc::VictorSP>(drivebaseSubLFVictorSP));
    
    drivebaseSubLBVictorSP.reset(new frc::VictorSP(1));
    lw->AddActuator("DrivebaseSub", "LBVictorSP", std::static_pointer_cast<frc::VictorSP>(drivebaseSubLBVictorSP));
    
    drivebaseSubRFVictorSP.reset(new frc::VictorSP(15));
    lw->AddActuator("DrivebaseSub", "RFVictorSP", std::static_pointer_cast<frc::VictorSP>(drivebaseSubRFVictorSP));
    
    drivebaseSubRBVictorSP.reset(new frc::VictorSP(14));
    lw->AddActuator("DrivebaseSub", "RBVictorSP", std::static_pointer_cast<frc::VictorSP>(drivebaseSubRBVictorSP));
    
    drivebaseSubSpeedControllerGroup1 = std::make_shared<frc::SpeedControllerGroup>(*drivebaseSubLFVictorSP, *drivebaseSubLBVictorSP , *drivebaseSubRFVictorSP , *drivebaseSubRBVictorSP);
    lw->AddActuator("DrivebaseSub", "Speed Controller Group 1", drivebaseSubSpeedControllerGroup1);
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
